@Task_Management_API_HostAddress = http://localhost:5126

GET {{Task_Management_API_HostAddress}}/weatherforecast/
Accept: application/json

### Login
POST https://localhost:7011/api/Auth/login
Content-Type: application/json

{
  "email": "employee@test.com",
  "password": "Password123!"
}
### Refresh
POST https://localhost:7011/api/Auth/refresh
Content-Type: application/json

{
  "refreshToken": "jb+SBSwxd8EkeoGORgqABcTz5GphEre01qsAAUNWiZs="
}