<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Resources\SharedResource.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\SharedResource.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Task_Management.Application\Task_Management.Application.csproj" />
  </ItemGroup>

</Project>
